project:
  type: website
  output-dir: docs

website:
  title: "Thomas Matheis"
  navbar:
    left:
      - href: index.html
        text: Home
        
      - text: Data Viz
        menu:
         - href: starbucks.html
           text: Starbucks
         - href: ufo.html
           text: UFO Sightings
           
      - text: Text Analysis
        menu: 
         - href: spotify.html
           text: Spotify
           
      - text: Simulation Study
        menu: 
         - href: test.html
           text: Guessing on a Test
           
      - text: Data Science Ethics
        menu: 
         - href: ethics.html
           text: Poorly Anonymized Data
           
      - text: SQL
        menu: 
         - href: policing.html
           text: Police Traffic Stops

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

 