project:
  type: website
  output-dir: docs

website:
  title: "Thomas Matheis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Data Viz
        menu:
         - starbucks.qmd
         - ufo.qmd

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

 