project:
  type: website
  output-dir: docs

website:
  title: "Thomas Matheis"
  navbar:
    left:
      - href: index.html
        text: Home
        
      - text: Data Vizualization
        menu:
         - href: starbucks.html
           text: Starbucks Beverages
         - href: ufo.html
           text: UFO Sightings
         - href: athletics.html
           text: Pomona-Pitzer Athletic Spending
         - href: registration.html
           text: 5C Pre-Registration
           
      - text: Text Analysis
        menu: 
         - href: spotify.html
           text: Spotify Wrapped Analysis
           
      - text: Statistical Simulations
        menu: 
         - href: test.html
           text: Guessing on a Test
         - href: hockey.html
           text: Hockey Player Birth Months
         - href: runners.html
           text: Start-Line Positions
         - href: swimmers.html
           text: Junior Swimming Powerhouses
         
           
      - text: Data Science Ethics
        menu: 
         - href: ethics.html
           text: Poorly Anonymized NYC Taxi Data
           
      - text: SQL
        menu: 
         - href: policing.html
           text: Analyzing United States Policing Data
      - href: presentation.html
        text: Presentation

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

 